### ISSUE TITLE
Post-processor for vagrant box for cloudstack

### ISSUE THREAD

**Issue by dduportal** [schubergphilis/packer-cloudstack#14]
Hi !

As we are trying to provide some "dev boxes" that our user can run in virtualbox as well as in the cloudstack (dependening on the pwoer of your local machine), i want to investigate further in that use case :
* A unique packer.json file with these sections :
  * Builders :
    * [x] "cloudstack" builder
    * [x] "virtualbox" builder
  * [x] Provisionners : a list of shell scripts, common to all my images (like install that thing, download that stuff, write that piece of file)
  * Post-processor :
    * [ ] A "vagrant" one which should be bound to my virtualbox artefact : the .ova and .mf file for vbox, a box-level Vagrantfile and it will generate my "metadata.json" saying that box will use virtualbox.
    * [ ] Another "vagrant" one for creating a lightweight baebox which is cloudstack bound - see https://github.com/klarna/vagrant-cloudstack/tree/master/example_box for more information.
  *  Push : As packer supports "push" operation, once your template has been built - https://packer.io/docs/templates/push.html -, we can enhance our use cases :
    * [ ] A push for cloudstack : for each cloudstack builder i use, i want to copy the "tmp" template already generated and created from the API, by packer-cloudstack plugin, to a "real named" template (e.g. : the packer build will create a "my-box-tmp" and packer build will ensure that my-box-tmp will become "my-box-final" for)
    * [x] A push for my other artefacts.

We are two packer-cloudstack related things :
* First is the functionnality to bind a post-processor to the build : generate a vagrant box for the vagrant-cloudstack plugin, from the template just generated
* Second is the functionnality to re-use the packer push step, in order to move our artficat (remote template) from a tmp state to a final state

I've just quickly written that issue, i think @Filirom1 and me can contribute and write those, but me have to validate the concept before rushing to the write.

Is it enough clear ? Do you need more context ? Do you agree or disagree ?

**Comment by mindjiver** [comment]
There used to be a post build processor for cloudstack/packer when everything was embedded inside packer.git . After I extracted the build into this plugin it didn't build anymore.

My biggest problem currently is that I have no access to a Cloudstack instance anymore, so I can't test any changes.

**Comment by mindjiver** [comment]
@dduportal now with the project transferred to people that can actually work on this perhaps it will be easier to get this working? :smile_cat:

**Comment by svanharmelen** [comment]
I'm going to close this up, as there is now an open PR with Packer to add a built-in CloudStack builder.
