### ISSUE TITLE
Transferring the project

### ISSUE THREAD

**Issue by miguelaferreira** [schubergphilis/packer-cloudstack#15]
hi @mindjiver 

As we discussed in https://github.com/klarna/vagrant-cloudstack/issues/62, I'm ready to move over the git tree from this repo to our organisation and then continue the development from there. 
However, our open-source policy requires an Apache 2.0 license. Would it be possible for you to change the license file on the repo?
It would be enough to replace the contents of the current license file with this: http://www.apache.org/licenses/LICENSE-2.0.txt

In additional, not to loose history of issues, PRs, etc, would it be possible for you to transfer the repo to me?
There is some documentation on how to do that here: https://help.github.com/articles/transferring-a-repository/

**Comment by mindjiver** [comment]
Since this is based off a part of the tree of Packer I kept the original license. I'm not sure it can be changed.

**Comment by miguelaferreira** [comment]
We've checked the Mozilla license, and our understanding is that, since this project is an extension to the original project ti would be allowed to change the license.

But if you rather not, than we can still work with this license, only we will never be able to change it ourselves because you wrote the code under the current license.

All-in-all it would be a great to help if you could change the license yourself. But if you don't want to, that's fine.

Then, there is only the issue of transferring the repo. Could you do that?

**Comment by mindjiver** [comment]
I'll check this later tonight, a bit busy here at work at the moment :smile:

**Comment by miguelaferreira** [comment]
Sure. No problem.

**Comment by miguelaferreira** [comment]
ping @mindjiver

**Comment by mindjiver** [comment]
Sorry, been busy. I have a "hack day" at work on Friday so I thought I would take a look at this.

**Comment by miguelaferreira** [comment]
Ok. Please let me know on Friday, some of my colleagues are getting impatient to start working on it :)
And, again, if it is too much trouble to go over the license issue, we can just transfer the repo and work with the current license. Thanks

**Comment by mindjiver** [comment]
Alright! So how do I transfer the project? Don't I need to be member of your org?

**Comment by miguelaferreira** [comment]
What we did with the vagrant plugin was to transfer it to my own account, and then I transfer it to our org.

**Comment by mindjiver** [comment]
Cool! Transferred!

**Comment by miguelaferreira** [comment]
Got it. Thanks a lot :+1:

**Comment by mindjiver** [comment]
First PR sent

**Comment by miguelaferreira** [comment]
Thanks :+1:  @svanharmelen will pick it up from now on
