### ISSUE TITLE
packer-cloudstack & 0.10.x ?

### ISSUE THREAD

**Issue by wico** [schubergphilis/packer-cloudstack#18]
Hej,

I know ... patches welcome ;), but I might ask anyway: Are there any plans to bump the code to be able to compile against latest packer (+ to update e.g. the broken references to code.google.com)?

Martin

**Comment by svanharmelen** [comment]
See issue #17 I actually started with the needed work, but got distracted half way through :disappointed: 

We do have an incentive ourselves as well to get this fixed, so it's back on my todo list. Yet I don't dare to make any promises on a timeline...

**Comment by wico** [comment]
That sounds good - thank you!

**Comment by svanharmelen** [comment]
I know, I know... It took waaaaay to long, but here it is: https://github.com/mitchellh/packer/pull/3909

**Comment by svanharmelen** [comment]
I'm going to close this one as progress on getting the CloudStack builder in Packer can be followed in issue #17
